### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by axtimwalde** [saalfeldlab/n5-aws-s3#13]
Hi @ctrueden, the current build fails after merging your recent PR, any ideas?

**Comment by ctrueden** [comment]
@axtimwalde The problem is due to changes in n5, specifically saalfeldlab/n5@cb37392e353cdde3d77cd509b407fc584a5276ee, although I don't understand why that commit breaks things here. But I know very little about this code.

-------------------

The failing tests are:
* `testDeepList(org.janelia.saalfeldlab.n5.s3.mock.N5AmazonS3BucketRootMockTest)`
* `testWriteReadDoubleBlock(org.janelia.saalfeldlab.n5.s3.mock.N5AmazonS3BucketRootMockTest)`
* `testRemove(org.janelia.saalfeldlab.n5.s3.mock.N5AmazonS3BucketRootMockTest)`
* `testWriteReadByteBlock(org.janelia.saalfeldlab.n5.s3.mock.N5AmazonS3BucketRootMockTest)`
* `org.janelia.saalfeldlab.n5.s3.mock.N5AmazonS3BucketRootMockTest`

> `com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: null; S3 Extended Request ID: null; Proxy: null)`

Tests were also failing in the melting-pot, so I disabled testing of this component (scijava/pom-scijava@1f2dcc608e2f6bad4c5f775b797e3b9279ce9a15) as a workaround.

**Comment by axtimwalde** [comment]
Ouch. I didn't test the PR before merging, and only checked whether it looked reasonable.  Could you may be file things that break as draft PRs instead of PRs?  Will dig into this as soon as I find time...

**Comment by ctrueden** [comment]
Sorry, I didn't know that #12 would break the build. And I thought it would be checked by the GitHub Actions workflow, but for some reason that workflow didn't run against the PR. Anyway, we need to fix the dependency skew between n5 and n5-aws-s3 regardless, right? Not merging the PR would only have masked the problem for longer, while shipping potentially incompatible components with Fiji.

**Comment by axtimwalde** [comment]
fixed by #14
